language: java

# Specify which branches/tags that we do not want to be built: r5.0.0-M5
branches:
  except:
    - /^r\d.*$/

before_install:
  - unset _JAVA_OPTIONS # https://github.com/travis-ci/travis-ci/issues/8408

install:
  - ./gradlew --version # Display Gradle, Groovy, JVM and other versions

jdk:
  - oraclejdk11

stages:
  - test
  - name: deploy
    if: (branch = master) AND (NOT type IN (pull_request))

jobs:
  include:
    - script: ./gradlew --stacktrace build
    - stage: deploy
      name: "Publish snapshot artifacts"
      env:
        # ORG_GRADLE_PROJECT_ossrhUsername
        - secure: vOVNqJ3ECL5W6X9M/MC7wUnZIDBOaleIsoAVQXajaL2U/B9I0HNNqjjeCmWoiUO8HViKBzDsJB2lo1+qiySgCsDeYW+6Rv1riFTyqGTv3PK4fiFKPzZXhh38EDkJa59hPwIs6yQm5UvClNZEEtnkiV1eOMS28UgWVeqbHhBwoJxRcj5rEExyxbFcEtCkfCGVRLuaJXTdI1wfZ/Dv3Cxe4yPo0FC8JW8p3kG6kstK+t3IpkjIVjX7NL2o0Zini/WFrIvHayrGIiliXijwcU9PxljVvtJkAh5gNbN15FmeIbG5PkUvzVam3pIAOMk3VhJJUu1cfJqcuILgKDbj8Pv3+G9mXD0Mpb5cbLBfCHQskp/k8vAGhURyoALyALpCW2DE03VUKv5X8kMop5o//5KHXxkAq6dzGunqeJy4sKIPBzcfWv6QVEtJJNROJKPe6R9DEqGvMM3D6Qc0QG3FBSKeiY18hWsSPS7j6qB0rnmHRq2tUa+63+wnabRLEptLumO/22bjxZQ6Xi3t7kGqy92AZcCPYUzHzb24BKgEr6NybfCP8PZgzeuFixUVYVxyZD7yRvtGSg49BT5O5OM+rrNOJfbySGuosjo+MuBvXt04t8/8SYJiJ1qbsFZXeVI3nq28VKgxOCjk6QYs3vcrS+KP1MIbAdMg7L2hO9goWxxH1Gs=
        # ORG_GRADLE_PROJECT_ossrhPassword
        - secure: CLrncz3oysmbaVSdYBzFp4zncpEGjyWKfTSDFVS4kfR6BtbX/3g1aSMpnxR91WysL0jB7N3Rd3WZrxIvMA28EMGo5tEXG3ow5Q8KeI4e8cET+gnvLS1z1+wP+/TqhcU9rBofLi46L7JzTs+PsCaRrzQc5YLW/aIqbGrA003Lo4tJ9cBHwmNa7YPUDE1zwmSpkMJp3CutUL1EzPm8Rx27vc13SSYCkxAsxShWSiRCCBb0803KOk/kWXpAu607rBy2seV5ltaVV+d7yc89bS96q8KpPSNuhBScCYwjHP3V9s05NGab7ErhEKpmcyGK/alCJXRGZUSZR4hRhdIwE/P1155f8mpaQCXk+acPL22QZHTXmp4y5FJlW4bsI/lyWyKtKT70r+ZCKbbZ+fXNB2TOQ7uMZpM5nfdOC6GcWnM/2WMDtZLNEwJ9Kg5PReiqy7ymvmUTxgd44/OH7fqgvoNATwQlbLc8nOU0vUbA2WWgCcLr+eLsLTjUQVlgxf6dQxa0fOud7APaKHdJwWQLYjIcm5mlMYBz445BnO4mylfSLHDTVyhK8xxfXRzi2PhTQb99Kh7z5Q0XWDtBjBcyE8Y75Crz4ayAW5hzDPzCTyPUCI+3BJoDDE6jE3qYzxETuPNojnhEFPb5DA5P2pPw4a2p5QMeoY430dtJsxyn/SQ9Voo=
      script: ./gradlew --stacktrace uploadArchives -x check
    - name: "Update snapshot documentation"
      env:
        # ORG_GRADLE_PROJECT_githubToken
        - secure: YvgOsZ7Dsc04xVM14FCleSpKflRzVo48Wmg+gr783sPhS1yocRE7yATZyeadzs9k13zTKLCMcRpx5URI5hvEMtjuq413by4aPEwSL97U4LiomSqXupTT1Vs5XKzJqeZuSJt5jVuu/uS0VewJgne4wxb8TCjEO7jMgE2wpaF1O7s+0iWzLrflCdRETuH6aoH8VEK89Ao8eQQuLWTS6XUkDSUhs0ojV+2m1TF2j4JpTdOjsDv/lEP9p7HsY7p1otCgbalzUFZzPNhQzCpebHzWV6SGXdPbolU+0rn7k+f4wnvr62C5j1NPb4y/P7r+0tEhDszJAwjcAkaS878iFRsvEwewV8pLxKlLNN92/+bTYG93rifBpbNC7VQ4z7w+sSgHAtE8CvNq4wkBtOiHdc2iNL63QVufTJfuoKzgxhJjG4hLNbdXGo2WLwTRBXUJit73wnLlzgBgTJb8/Bv59KPM57it94XRiCph5hLnobRaOpEoqoHROnHXBQoKBWkDMGgY3fwEXvQDOIZdr+XcLytwWaMky3GaaCaOjvF5v3IgLrYgfEy9oFOM/IGI15AvqyXU9Xkk/FmFeU2pQhLjLrBRoEqaicz5VskNW22yZqk+yv5K1o5aGFS+6AbJMj97aETxshlQ21UasR8taYntz3AtqItUTAOKhDJL2VWKRi3mllg=
      script: ./gradlew --stacktrace publishGhPages
